name: dart_pdf_reader
description: Small pure-dart library for parsing PDF files. Supports reading all pdf structures
version: 0.0.5
repository: https://github.com/NicolaVerbeeck/dart_pdf_reader

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  charset: ^2.0.0
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  dcli: ^2.3.0
