name: dart_pdf_reader
description: Small pure-dart library for parsing PDF files. Supports reading all pdf structures
version: 2.1.0
repository: https://github.com/NicolaVerbeeck/dart_pdf_reader
issue_tracker: https://github.com/NicolaVerbeeck/dart_pdf_reader/issues
topics: [ pdf, parser ]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ">=3.4.9 <5.0.0"
  charset: ^2.0.1
  collection: '>=1.17.0 < 2.0.0'
  image: ^4.5.4
  meta: '>=1.9.1 < 2.0.0'


dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
  mocktail: ^1.0.0
  convert: ^3.1.1

funding:
  - https://buymeacoffee.com/nicolaverbn
  - https://ko-fi.com/nicolaverbeeck