name: dart_pdf_reader
description: Bare-bones PDF reader library in pure dart
version: 0.0.1
repository: https://github.com/NicolaVerbeeck/dart_pdf_reader

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  charset: ^1.2.0
  image: ^4.0.17
  meta: ^1.9.1
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
